### ISSUE TITLE
Problem in 3.0 iOS Build Post Process on case-sensitive OS

### ISSUE THREAD

**Issue by dantasulisses** [devtodev-analytics/Unity-sdk-3.0#1]
Hi!
Currently there is a issue in the DTDPostProcessAnalytics class, due to case-sensivity of file names in some OS's (Linux, for instance)
At line 36 of this script, there is this code:
```
AddAnalyticsFramework(pathToBuiltProject, project, targetGuid,
        PlayerSettings.iOS.sdkVersion == iOSSdkVersion.DeviceSDK
                    ? Path.Combine("Plugins", "DevToDev", "Analytics", "iOS", DEVICE)
                    : Path.Combine("Plugins", "DevToDev", "Analytics", "iOS", SIMULATOR));
```
The problem is, the iOS plugin folder in the UnityPackage is written "IOS" (notice the upper case 'I')
![Captura de Tela 2022-01-12 às 12 04 19](https://user-images.githubusercontent.com/10074934/149166011-c44674e6-ce6c-44d7-b984-9a13308b1f17.png)
This causes the PostProcess don't work, which breaks the Xcode project build. This is a problem mainly when building in Linux, in which filenames and folders are case-sensitive.

The fix is simple, and would be nice to be added in a future relese: just changing the above code to upper case 'IOS'

**Comment by Blakend2** [comment]
Hi @dantasulisses! Thanks for your comment, we will fix this issue in the next release very soon.

**Comment by Blakend2** [comment]
@dantasulisses, we fixed this issue in last release https://github.com/devtodev-analytics/Unity-sdk-3.0/releases
