### ISSUE TITLE
Android crash in 3.6.4

### ISSUE THREAD

**Issue by paulo-lafeta** [devtodev-analytics/Unity-sdk-3.0#11]
Hi,

I'm updating DevToDev SDK in our project from 2.X to 3.6.4, on Unity 2021.3.28f1.

When running an Android build, game crashes during function call: _DTDAnalytics.Initialize_ , with the following log:

`java.lang.Exception: Missing dependency com.devtodev:android-google`

Then, I read in documentation that if the project uses Google Ad ID, it needs to import DTDGoogle.unitypackage, which I did next. 

After DTDGoogle.unitypackage got imported, the crash still happens, but now with a different log:

`No virtual method getGooglePlayInstantParam()Z in class Lcom/android/installreferrer/api/ReferrerDetails; or its super classes (declaration of 'com.android.installreferrer.api.ReferrerDetails'`

OBS: Our project uses Google Play Games, Google Play Services, Facebook SDK, and OneSignal SDK.

Any clue what might be causing it?

**Comment by kaikristo** [comment]
Hello, try to add < androidPackage spec="com.android.installreferrer:installreferrer:2.2" /> in the \Assets\DevToDev\Analytics\Editor\AppDependencies.xml file.

**Comment by paulo-lafeta** [comment]
There was no AppDependencies.xml in this folder, but a GoogleDependencies.xml file, which I added this line and fixed the crash. Thank you!

**Comment by paulo-lafeta** [comment]
There was no AppDependencies.xml in this folder, but a GoogleDependencies.xml file, which I added this line and fixed the crash. Thank you!
