### ISSUE TITLE
Update from 3.6.5 to 3.8.1

### ISSUE THREAD

**Issue by frbodya** [devtodev-analytics/Unity-sdk-3.0#14]
Hello, I have prev version, 3.6.5, after i try to update to 3.8.1, I get in Xcode such Errors:

Undefined symbols for architecture arm64:
  "_getEmail", referenced from:
      _UserCard_getEmail_m2BC378BCB6B727B603EA8F27DC0E30D142D98FE6 in libGameAssembly.a[9](q56owsdime2w.o)
  "_getGender", referenced from:
      _UserCard_getGender_m7FA35ABC224AF21873A415042E84FAC3B3E3DEE7 in libGameAssembly.a[9](q56owsdime2w.o)
  "_setEmail", referenced from:
      _UserCard_setEmail_mFDF8844CBF41C12400D284E7E0F0A9EE5813811D in libGameAssembly.a[9](q56owsdime2w.o)
  "_setGender", referenced from:
      _UserCard_setGender_m36FDA41DE331A8BBA54CAC65BE8A816ED2FFFE3C in libGameAssembly.a[9](q56owsdime2w.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kaikristo** [comment]
1. Remove Devtodev folder from plugins folder
2. Reimport a package v3.8.1
3. If error still happens - try to increase the stripping level
