### ISSUE TITLE
Error while building for iOS with version 3.8.1

### ISSUE THREAD

**Issue by WalkMeMobileSolutions** [devtodev-analytics/Unity-sdk-3.0#15]
We just added the DevtoDev package to our Unity project.

It is working without any issue for Android, but when we try to build for iOS we get the following error:

DirectoryNotFoundException: Source directory does not exist or could not be found: {sourceDirName}
DevToDev.Analytics.Editor.DTDPostProcessAnalytics.DirectoryCopy (System.String sourceDirName, System.String destDirName, System.Boolean copySubDirs, System.String[] specificExtensions) (at ./Library/PackageCache/com.devtodev.sdk.analytics@16d485d2ac/Editor/Analytics/DTDPostProcessAnalytics.cs:143)
DevToDev.Analytics.Editor.DTDPostProcessAnalytics.AddAnalyticsFramework (System.String projectPath, UnityEditor.iOS.Xcode.PBXProject project, System.String targetGuid, System.String frameworkPath) (at ./Library/PackageCache/com.devtodev.sdk.analytics@16d485d2ac/Editor/Analytics/DTDPostProcessAnalytics.cs:79)
DevToDev.Analytics.Editor.DTDPostProcessAnalytics.OnPostProcessBuildIOS (UnityEditor.BuildTarget target, System.String pathToBuiltProject) (at ./Library/PackageCache/com.devtodev.sdk.analytics@16d485d2ac/Editor/Analytics/DTDPostProcessAnalytics.cs:53)
DevToDev.Analytics.Editor.DTDPostProcessAnalytics.OnPostProcessBuild (UnityEditor.BuildTarget target, System.String pathToBuiltProject) (at ./Library/PackageCache/com.devtodev.sdk.analytics@16d485d2ac/Editor/Analytics/DTDPostProcessAnalytics.cs:23)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fd2d3e9b010a4ba4b3fdc0456cd6b40b>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:190)

Is there a way to fix this? We tried with a clean build folder but we get the same error every time.

**Comment by kaikristo** [comment]
can you send me a DTDPostProcessAnalytics.cs? In PackageCaches/com.devtodev.analytics/Editor/Analytics ?

**Comment by kaikristo** [comment]
fixed in v3.8.2
