### ISSUE TITLE
Unexpected duplicate tasks. Command: SignatureCollection /Users/.../DTDAnalyticsiOSUnity.xcframework-ios.signature

### ISSUE THREAD

**Issue by khrchvnkv** [devtodev-analytics/Unity-sdk-3.0#16]
Unity 2022.3.36
DevToDev 3.8.3
XCode 15.4

After updating the Unity version to version 2022.3.36 and Xcode to 15.4, an error "Unexpected duplicate tasks. Command: SignatureCollection /Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-gbijmbeeepnwijbeimbaluhazfxw/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/DTDAnalyticsiOSUnity.xcframework-ios.signature" occurs. Before that, the Unity version 2021.3.22 and Xcode 15.2 were used and the build was assembled without errors

I tried to clean the DerivedData folders and run the CleanBuildFolders command - the result is the same

Thanks in advance!

**Comment by kaikristo** [comment]
fixed in v3.8.4
