### ISSUE TITLE
[Android] Crash on app start

### ISSUE THREAD

**Issue by dreding** [devtodev-analytics/Unity-sdk-3.0#2]
Hello,

I receive this fatall exception when try to run my android app build with d2d sdk integrated. I've tryed initialization try own class and try devtodev object - all have same result. 

Crash log from logcat.

2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime FATAL EXCEPTION: pool-14-thread-1
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime Process: com.solinteractive.quiz, PID: 13563
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime java.lang.NoSuchMethodError: No virtual method getGooglePlayInstantParam()Z in class Lcom/android/installreferrer/api/ReferrerDetails; or its super classes (declaration of 'com.android.installreferrer.api.ReferrerDetails' appears in /data/app/~~da3qlo8aQ-USxZ7UWiunkQ==/com.solinteractive.quiz-MbRw56VJ9YZ7pZPlOSWaeg==/base.apk)
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime 	at d0.h$b$b.invoke(ReferrerClient.kt:39)
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime 	at com.devtodev.analytics.internal.queue.QueueManager$Companion.d(QueueManager.kt:1)
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime 	at com.devtodev.analytics.internal.queue.-$$Lambda$ZAjvo-fi54tKNKnlwmGwSbmlW8g.run(Unknown Source:2)
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022.07.18 22:20:27.178 13563 13695 Error AndroidRuntime 	at java.lang.Thread.run(Thread.java:923)

Unity version 2021.3.5f1

**Comment by ArtemHarmashKG** [comment]
same to me

**Comment by kaikristo** [comment]
Sorry for the late response. We will look at this problem.

**Comment by surgentdavid** [comment]
Same issue here, android unity 2020.3 LTS, API target 31. Fixed by manually adding install referrer dependency and permission in android manifest

`<androidPackages>
    <androidPackage spec="com.android.installreferrer:installreferrer:2.2" />
</androidPackages>`

`<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"/> `

**Comment by orbit1987** [comment]
Yes that's right. Need to add com.android.installreferrer:installreferrer:2.2 for correct work.
