### ISSUE TITLE
Newtonsoft json plugin version conflict with other plugins which use different version.

### ISSUE THREAD

**Issue by ArshakKroyan** [devtodev-analytics/Unity-sdk-3.0#4]
We have versioning problems with Unity Newtonsoft json plugin.
Devtodev uses some fixed version in its .dll.
Other plugins use different versions.

In order to skip this issue we do unwanted workarounds.
But as the project grows, and we integrate new plugins which themselves also use Newtonsoft, fixing the issue becomes harder and harder.

Could you please make Devtodev depend on Newtonsoft packages, requiring some minimal version, so the other packages also could use higher versions of the Newtonsoft?
Or some other solutions, which wouldn’t conflict with other Newtonsoft usages.

**Comment by kaikristo** [comment]
If you have a conflict between different versions of newtonsoft json :
1) delete newtonsoft in the assets/plugins/devtodev folder
2) uncheck box 'validate references' in the inspector for conflicting dll
! devtodev sdk work only with newton v.12 or newer.

**Comment by kaikristo** [comment]
We recommend using newtonsoft distributed via unity package manage. It is this version that we use.

**Comment by ArshakKroyan** [comment]
Thanks.
