### ISSUE TITLE
Wrong asmdef configuraration for devtodev.sdk.messaging

### ISSUE THREAD

**Issue by andreimilkov** [devtodev-analytics/Unity-sdk-3.0#8]
**Unity 2020.3.21
devtodev v3.5.0**

Packages/com.devtodev.sdk.messaging/Editor/com.devtodev.sdk.messaging.Editor.asmdef

Platform set "Any Platform".
When Android build:

> Library\PackageCache\com.devtodev.sdk.messaging@2e8b6cc3eb\Editor\Messaging\DTDGoogleServicesConverter.cs(7,19): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
> 
> Library\PackageCache\com.devtodev.sdk.messaging@2e8b6cc3eb\Editor\Messaging\DTDGoogleServicesConverter.cs(8,19): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
> 
> When build android, get errors:
> Library\PackageCache\com.devtodev.sdk.messaging@2e8b6cc3eb\Editor\Messaging\DTDGoogleServicesConverter.cs(11,43): error CS0246: The type or namespace name 'IPreprocessBuildWithReport' could not be found (are you missing a using directive or an assembly reference?)
> 
> Library\PackageCache\com.devtodev.sdk.messaging@2e8b6cc3eb\Editor\Messaging\DTDGoogleServicesConverter.cs(106,35): error CS0246: The type or namespace name 'BuildReport' could not be found (are you missing a using directive or an assembly reference?)

Fix pls, .asmdef Platform should only for Editor.
After this fix, build was succesed.

**Comment by kaikristo** [comment]
Will be fixed in 3.5.1
